### ISSUE TITLE
请问能从maven库里面下载这个java SDK吗？

### ISSUE THREAD

**Issue by wangjia2016** [kuaidi100-api/java-demo#1]
请问能从maven库里面下载这个java SDK吗？

**Comment by wangjia2016** [comment]
@Liguanqin 预计什么时候会提供，迫切需要，谢谢 已经用你们的接口很多年了

**Comment by Liguanqin** [comment]
您好，
        抱歉，短时间内安排不上呢。



1186749489@qq.com
 
发件人： 幽灵柯南
发送时间： 2020-09-16 17:34
收件人： kuaidi100-api/java-demo
抄送： liguanqin; Mention
主题： Re: [kuaidi100-api/java-demo] 请问能从maven库里面下载这个java SDK吗？ (#1)
@Liguanqin 预计什么时候会提供，迫切需要，谢谢 已经用你们的接口很多年了

**Comment by kuaidi100-api** [comment]
已支持
