### ISSUE TITLE
引入kuaidi100的依赖后 项目的日志全部都不输出了

### ISSUE THREAD

**Issue by lhc007** [kuaidi100-api/java-demo#4]
如题

**Comment by kuaidi100-api** [comment]
应该是logback包冲突了，引入的时候把我们的排除掉就好

**Comment by lhc007** [comment]
> 应该是logback包冲突了，日期的时候把我们的排除掉就好

排除后仍没效果,请问还有其他可能么
![image](https://user-images.githubusercontent.com/76759825/103326318-ce2e1180-4a8a-11eb-8e1a-8cbb3b5ff916.png)

**Comment by kuaidi100-api** [comment]
用1.0.1这个版本试试，剔除掉了logback的引入
<dependency>
            <groupId>com.github.kuaidi100-api</groupId>
            <artifactId>sdk</artifactId>
            <version>1.0.1</version>
        </dependency>

**Comment by lhc007** [comment]
> 用1.0.1这个版本试试，剔除掉了logback的引入
> 
> com.github.kuaidi100-api
> sdk
> 1.0.1

1.0.1版本无法下载

**Comment by kuaidi100-api** [comment]
![image](https://user-images.githubusercontent.com/68226294/103327640-58c53f80-4a90-11eb-8e92-075227db08b1.png)
这样引入不了吗？

**Comment by lhc007** [comment]
给同事的试了一下可以,我这把1.0.0删了之后在试试 麻烦你了.

**Comment by lhc007** [comment]
> ![image](https://user-images.githubusercontent.com/68226294/103327640-58c53f80-4a90-11eb-8e92-075227db08b1.png)
> 这样引入不了吗？

可以了 谢谢
